### ISSUE TITLE
How to make the results better

### ISSUE THREAD

**Issue by Armixy** [OpenGP/htrack#22]
Finally, I can run the codes, but the tracking result is not as good as your video, how can I make it better? And I wore a blue wrist band.

**Comment by ataiya** [comment]
1. use the correct hardware, we used a 4GHz i7 w/ a GTX980. If the framerate is below 60FPS you cannot expect the algorithm to run as well as you see in the videos. I saw you were using a laptop in previous examples, that would be a bad idea (I used a laptop for dev, but the desktop for real-time stuff)
2. make sure the ROI given by the wristband is correct, there is an option in the htrack_atb you can toggle to see the hand ROI. If that's off, then the algorithm will not perform well
3. make sure you adjust the shape of the template to your hand. Anastasia told me the model works a bit better on me/matthias than on hers. So slimmer hands might be a bit of an issue.

**Comment by Armixy** [comment]
1. My graphic card is GTX 970m, and the framerate is about 25-45 FPS.
2. There is no ROI toggle in the setting panel.
3. how to adjust the shape of template to my hand?

**Comment by ataiya** [comment]
1. there is a massive difference between a GTX980 and a GTX970m (the first is a desktop, the latter is a mobile GPU). That's why you get only 25 instead of 60.
2. see the show_hand and show_wband in this file (linked to the UI) https://github.com/OpenGP/htrack/blob/747b40f7a07f2bc0530587fae8dcf6fa31d25ee1/tracker/HandFinder/HandFinder.h
3. see the keyboard shortcuts in the atb application
4. that's done externally (we bake tracking parameters to FBX, then import it in maya and link it to the skinned model). This feature is not available, nor will be
